version: '3.8'

services:
  # Serviço para o Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - rabbitmq
    ports:
      - "9000:9000"

  # Serviço para o Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel_network

  # Serviço para o RabbitMQ
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - laravel_network

  # Serviço para o Vue.js (Frontend)
  frontend:
    image: node:18
    container_name: vue_frontend
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    networks:
      - laravel_network
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

networks:
  laravel_network:
    driver: bridge
